### ISSUE TITLE
Submit to OCA/pos?

### ISSUE THREAD

**Issue by robinkeunen** [Fkawala/pos_addons#1]
Hi @Fkawala , 

I'm working for Coop IT Easy, we host Le Nid's code on our servers. We would like to avoid pointing to many personal repositories. Could you submit the module `pos_reset_search` to the OCA/pos repository? I'm sure it could be useful to many others.

I can also do it myself submitting the code in a PR under your name.

We installed [pos_search_accented_unaccented](https://github.com/coopiteasy/addons/tree/9.0/pos_search_accented_unaccented) at Le Nid. Maybe we could do a common PR on oca/pos merging the code from your module `pos_accented_search` and ours.

All the best,

**Comment by Fkawala** [comment]
Howdy! 

Great idea, thank you! Should I go ahead and do the PR based on a7d76455e3f931ac3a9b6c017ae74318f774ee2e? 

Best regards

**Comment by robinkeunen** [comment]
Yep, you can go from there, module per module. Tag me on the PR so I can review and make the review process faster :-)

**Comment by Fkawala** [comment]
I'll do so once I'll have removed those damn .pyc files that should be gone already. Also, would you have a better `icon.png` file to suggest than our org's logo?

**Comment by robinkeunen** [comment]
If you submit it to the OCA, you should have the .gitignore correctly configured to ignore the .pyc. 

Same for the logos, submitting to the OCA, you'll have to use the [readme-generator](https://github.com/OCA/maintainer-tools/blob/master/README.md#readme-generator). The generator will fetch the logo from the oca directly.

**Comment by Fkawala** [comment]
Ok, I'll have a look at the OCA contribution guidelines. On a related note, do you think the other add-on [pos_reset_search](https://github.com/Fkawala/pos_addons/tree/9.0/pos_reset_search) should be submitted to OCA?

**Comment by robinkeunen** [comment]
Yes, I think you could submit `pos_reset_search` as well.

I just had a chat with Michel: we’d like to keep the responsibility to deploy the code on the server as we provide support and maintenance for le Nid. But we are really keen on reviewing, deploying and integrating your PR into the codebase (pos or [otherwise](https://github.com/beescoop/Obeesdoo))  :-)

**Comment by Fkawala** [comment]
I created https://github.com/OCA/pos/pull/444.
